creation_rules:
  - path_regex: '.*'
    encrypted_comment_regex: 'sops:encrypted'
    age: 'age10ey0lcup4zpjqcknpxw7enpsagn674nm634f2u75trfr5t62uq5qdjuxzv'
stores:
  json:
    indent: 2
  json_binary:
    indent: 2
  yaml:
    indent: 2
